### PR TITLE
Added encoding parameter to initializer.

### PR DESCRIPTION
**Pull request by dbowen**

### CODE REVIEW

**Comment by dbowen** [comment]
Updated to fix unit tests.  I added the UTF8 default to the convenience initializer, but the base initializer requires it to be specified.

**Comment by naoty** [comment]
@dbowen Thank you for PR! I want to keep the signature of the convenience initializer. Even if you add a default value for the encoding parameter, the completion for the initializer includes the parameter. So the default value should be given in the initializer, and the signature should be kept.

**Comment by dbowen** [comment]
No problem.  I updated it to include a second convenience initializer to support encoding options so your original one maintains the same signature as before.

**Comment by naoty** [comment]
LGTM! :+1:

**Pull request merged**
